### ISSUE TITLE
托盘气泡无法关闭以及每次打开语音提示问题

### ISSUE THREAD

**Issue by Catnipll** [miaomiaosoft/PandaOCR.Pro#11]
作者大大辛苦了！

1、最新版 PandaOCR.Pro V5.31设置内，“程序提示方式”明明已经选择了禁用，但是每次打开还有右下角提示通知。

2、能不能在设置内开启一个选项，选择可以关闭每次打开时的语音——“欢迎使用PandaOCR中意版”，还是粤语版的。这样电脑开着声音每次都很不方便。
ps：我翻以前的issue，发现有人提过，可是按照那个issue里方式，每次更新完后的第一天就得静音，能否设置一个永久的开关呢？

谢谢大佬！

**Comment by miaomiaosoft** [comment]
程序提示方式 能禁用的是使用接口中的提示，程序启动时的欢迎提示无法禁用。

将朗读音量设为0就行了，但如果你又需要朗读那只能等第二天它会自动禁用打开时的语音。

**Comment by Catnipll** [comment]
> 程序提示方式 能禁用的是使用接口中的提示，程序启动时的欢迎提示无法禁用。
> 
> 将朗读音量设为0就行了，但如果你又需要朗读那只能等第二天它会自动禁用打开时的语音。

收到~大佬辛苦了~
