### ISSUE TITLE
图片里面有某种颜色的水印

### ISSUE THREAD

**Issue by asdfj2381k** [miaomiaosoft/PandaOCR.Pro#12]
![image](https://user-images.githubusercontent.com/56584082/124354685-c1f45e00-dc3f-11eb-905b-1155251f3984.png)

背景：我现在看的电子书有蓝色的水印，我想识别的时候，软件自动忽略这种颜色。

想法：软件在设置里加入：取色棒，让我手动抓取水印的RGB。   以后每次识别时，软件自动把这些颜色去掉。

（其实一般的电子书都只有黑色，如果能只识别黑色的字，倒也方便快捷）

**Comment by asdfj2381k** [comment]
更多截图（1）.png

![image](https://user-images.githubusercontent.com/56584082/124354793-61195580-dc40-11eb-9e99-19180ec8f689.png)

**Comment by miaomiaosoft** [comment]
你这个其实邻近像素点都不是同一种颜色，都是深浅不一的，所以程序上不好处理，需要先人工或其他工具去除。
当然你也可以尝试不同的OCR接口，有些可能会忽略这种斜向的水印。

**Comment by asdfj2381k** [comment]
明白了，谢谢回复。
