### ISSUE TITLE
不希望占用Ctrl+c热键，希望跟截图热键一样支持修改

### ISSUE THREAD

**Issue by mc373906408** [miaomiaosoft/PandaOCR.Pro#13]
不希望占用Ctrl+c热键，希望跟截图热键一样支持修改

**Comment by miaomiaosoft** [comment]
并没有占用这组键

**Comment by mc373906408** [comment]
开启软件后Ctrl+c，经常无法复制我想要复制的内容，我需要复制多次才可以

**Comment by miaomiaosoft** [comment]
那就禁用 双击复制功能

**Comment by mc373906408** [comment]
但是我又希望有一个快捷的翻译方式，所以支持一个快捷键进行快速读取剪切板的文字进行翻译

**Comment by miaomiaosoft** [comment]
这个功能有时失效可能和当前复制的窗口有关，网页上复制似乎没有问题，还需要日后排查优化再说，目前就只能这样，你可以装个“Clipx”小工具并开启复制音效功能，这样只要复制成功就会播放音效，如果失败则无音效

**Comment by mc373906408** [comment]
好的，谢谢

**Comment by mc373906408** [comment]
我在QT Creator软件上无法复制的情况发生的频率很高，有时候会复制为其他的文字（可能不是本软件的问题）。我退出程序之后恢复正常，我现在只能是需要翻译的时候才启动程序

**Comment by miaomiaosoft** [comment]
方便的话加群私群主，我可能要远程在你电脑上看看什么情况 700041212

**Comment by miaomiaosoft** [comment]
最新版本增加了“监听复制”功能，如果双击复制在你的系统环境使用不佳可以换用这个解决。
