### ISSUE TITLE
旧版的识别后自动复制到剪切板功能很方便，期望在专业版中也会有

### ISSUE THREAD

**Issue by fairyland-cat** [miaomiaosoft/PandaOCR.Pro#14]

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2021-7-9_10-59-55](https://user-images.githubusercontent.com/4084875/125017232-495d2980-e0a5-11eb-9fd7-2d4114a780ae.jpg)

这不是？

**Comment by fairyland-cat** [comment]
哦哦，可能是我没找到，赞👍
