### ISSUE TITLE
请问能否添加两个新功能？

### ISSUE THREAD

**Issue by lianxinsuo** [miaomiaosoft/PandaOCR.Pro#15]
1、老板键
就是字面意思啦，按一下就能立刻隐藏飘屏字幕的那种按键~

2、针对日文文本的纵向识别功能
因为有很多图片中，日文是从上至下，由右及左的排列方式，导致无法用pandaOCR识别并翻译，实在是很棘手，所以想问下这种功能能够实现吗？

以上。谢谢！

**Comment by miaomiaosoft** [comment]
1. 会考虑
2. 这个和你选择的OCR引擎有关，而不是由软件来实现，OCR要支持日文和竖排识别，百度OCR的高精度接口和有道OCR应该可以

**Comment by dovela** [comment]
“日文是从上至下，由右及左的排列方式”，使用高级功能的屏幕对照翻译配合腾讯ocr和腾讯翻译，倒是勉强可以翻译，但是文字是横置的，顺时针旋转了90度
![QQ截图20211113212403](https://user-images.githubusercontent.com/33590269/141645464-0f366a9a-bde7-4eaa-a384-6ec57d787cc9.png)
![QQ截图20211113212416](https://user-images.githubusercontent.com/33590269/141645474-c655fde9-8fe0-4bd7-bd09-55e26cfff639.png)

**Comment by miaomiaosoft** [comment]
文本方向颠倒功能已经在最新版本中提供，文本区右键菜单启用。
至于老板键，其实你直接按下截图快捷键（默认为F4）即可隐藏所谓的字幕。
