### ISSUE TITLE
截图时会自动放大的问题

### ISSUE THREAD

**Issue by wsbhacker** [miaomiaosoft/PandaOCR.Pro#16]
截图组件无论选择哪个,截图的时候都会放大屏幕导致无法截取边缘内容
截图前:
![image](https://user-images.githubusercontent.com/10154415/126055827-79ea97b6-5f56-418f-a1d2-d43c14b0012b.png)
截图后:
![image](https://user-images.githubusercontent.com/10154415/126055835-399eb9f3-8260-47ac-a718-5a599bbe6f2b.png)

**Comment by miaomiaosoft** [comment]
不是有现成教程吗？
https://support.qq.com/products/322047/faqs/95279

**Comment by wsbhacker** [comment]
谢谢,  耽误时间了.
