### ISSUE TITLE
高DPI屏幕显示异常

### ISSUE THREAD

**Issue by CarrotChou** [miaomiaosoft/PandaOCR.Pro#17]
截图识别功能在高DPI屏幕上会出现显示异常，软件里内置的QQ截图需要背锅。

![iShot2021-07-19 18 28 46](https://user-images.githubusercontent.com/80279323/126147964-8d925539-5c97-4ee0-b2ed-0c43c2bed1ad.jpg)

https://user-images.githubusercontent.com/80279323/126148003-b64dd05a-f998-4c06-a3b5-51b09b45106a.mp4

**Comment by miaomiaosoft** [comment]
程序没有原生支持高分屏，所以需要按教程设置一下属性：
https://support.qq.com/products/322047/faqs/95279

**Comment by miaomiaosoft** [comment]
之前旧版我发现你在微信上也帮忙推荐这个软件，我想送你个专业版激活码，用邮件发机器码给我就行，激活窗口下有我的邮箱

**Comment by CarrotChou** [comment]
> 之前旧版我发现大佬在微信上也帮忙推荐这个软件，想送你个专业版激活码，如果需要可以用邮件发机器码给我，激活窗口下有我的邮箱

谢谢你的好意，目前我在用macOS，暂时我不需要😂以后需要了，我再联系你。

**Comment by miaomiaosoft** [comment]
> > 之前旧版我发现大佬在微信上也帮忙推荐这个软件，想送你个专业版激活码，如果需要可以用邮件发机器码给我，激活窗口下有我的邮箱
> 
> 谢谢你的好意，目前我在用macOS，暂时我不需要以后需要了，我再联系你。

OK

**Comment by miaomiaosoft** [comment]
最新版本已优化此问题：https://github.com/miaomiaosoft/PandaOCR.Pro/releases
