### ISSUE TITLE
点右上角关闭后的bug

### ISSUE THREAD

**Issue by toohanabi** [miaomiaosoft/PandaOCR.Pro#19]
点右上角的关闭  则会出现图3所示情况
如果是最小化，则正常，不会出现该情况
后来发现拖动窗口也会出现该bug     最后录了个屏

<img width="632" alt="Snipaste_2021-08-24_21-14-19" src="https://user-images.githubusercontent.com/77424375/130623318-921605d0-ac7d-414a-9593-4837f1d7892d.png">
<img width="637" alt="Snipaste_2021-08-24_21-13-57" src="https://user-images.githubusercontent.com/77424375/130623270-b99f7832-a5e8-4852-ad9f-bfe3987c6510.png">
<img width="683" alt="Snipaste_2021-08-24_21-14-10" src="https://user-images.githubusercontent.com/77424375/130627963-c949e1a5-de24-4354-a302-db54e0c855c8.png">

https://user-images.githubusercontent.com/77424375/130624855-2163c17e-030d-43bc-acd1-7e0a636c84ff.mp4

**Comment by toohanabi** [comment]
第一次发github  不知道为什么出现这种情况   
<img width="276" alt="Snipaste_2021-08-24_21-35-22" src="https://user-images.githubusercontent.com/77424375/130626181-877dad87-da7f-4b6f-ac37-408fca9b9eef.png">
<img width="307" alt="Snipaste_2021-08-24_21-35-27" src="https://user-images.githubusercontent.com/77424375/130626191-cdef1b0b-6bd3-47d1-a3e4-ec35cc8e1605.png">

**Comment by toohanabi** [comment]
好吧  我知道了   第一次玩GitHub  我用了Chrome的翻译   不好意思了

**Comment by miaomiaosoft** [comment]
这个应该重启下程序就好了吧，很少见的BUG

**Comment by toohanabi** [comment]
是的，重启了之后就好了
