### ISSUE TITLE
双屏模式的截图的选择项缺少提示

### ISSUE THREAD

**Issue by yi-Xu-0100** [miaomiaosoft/PandaOCR.Pro#2]
双屏模式的截图的下方没有选择项，使用 gdi 截图又只能截一个屏的。下方的选择项后面能支持吗？挺方便的

**Comment by miaomiaosoft** [comment]
目前就只能这样，我自己也没有双屏，即使我想实现也没有硬件环境测试是否可行

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 好的，希望以后支持，非常感谢，使用上感觉很方便！

**Comment by miaomiaosoft** [comment]
目前的设想是在使用非GDI截图组件时，按住相应按键可以达到和选择栏一样的功能。
比如：
截图的同时按住主键区的“1键”，截图完成后就是搜图
“2键”是图床，依此类推至“5键”为公式

此功能将在下个新版实现

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft emmm, 由于键盘的限制，我按 F4 都需要多加一个 fn，如果再加其他的键去选择，可能不太好弄，能否提供快捷键设置。即，对不同模式可以指定不同的快捷键。谢谢！

**Comment by miaomiaosoft** [comment]
你理解错了，是在截图后按，也就是鼠标已经选取区域准备点确定时再按键而不是替代截图快捷键

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 好的！那没问题！非常感谢！

**Comment by miaomiaosoft** [comment]
另外，触发截图的方式有很多种，可以把鼠标移到屏幕左上角、或如果鼠标有侧键也可以启用侧键截图，都不需要按F4，具体可以查看高级设置和配置文件

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 嗯嗯，有看到，快捷键习惯了，鼠标移到屏幕左上角也很方便，正在适应 😊

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 试验了最新版，功能上没有问题。不过，有没有办法加上提示吗？我完全不知道我应该按哪个，得先翻下更新日志才知道自己按哪个。当然可能用的多了会知道，但是估计其他的表格什么的本身用的也少就是。 😁

**Comment by miaomiaosoft** [comment]
明白，下版本增加提示

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 你好，我看到最新版有截图提示，我也选择启用，重启生效了应该，但是双屏截图时没有任何效果？不太知道这个提示是什么形式？

还有一个问题，我看到日志中有提到：

>优化 边角触发截图功能（尝试解决在系统锁屏或进入UAC状态时误触发的问题）

这个在双屏模式下是会触发的，但是我实验了下，好像还是没有解决。

**Comment by miaomiaosoft** [comment]
你换其他截图组件就知道是什么形式了，双屏截图组件的形式有点不一样，显示两秒会自动消失。
由于我没有双屏，所以此问题我是盲猜的解决方法，不行的话还是只能禁用边角截图，目前只能这样。

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 哦，好的，我在快速截图中看到了！没注意到，在双屏里也看到了！边角截图的话，我暂时禁用吧。谢谢！

**Comment by yi-Xu-0100** [comment]
有提示的话，我这个 issue 先关闭了！

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 使用了最新版，在双屏下的“在系统锁屏或进入UAC状态时误触发的问题”，已解决！
