### ISSUE TITLE
无法支持 Window 10 的提供的 Beta - UTF8 选项问题

### ISSUE THREAD

**Issue by wolovejing** [miaomiaosoft/PandaOCR.Pro#20]
## 缺陷描述
在 Windows 10 中微软引入了"非 Unicode 程序的语言" 设置中，多了一个“Beta 版：使用 Unicode UTF-8 提供全球语言支持”的选项，只要勾选了该选项就会导致程序显示界面乱码
## 重现此问题的步骤
请描述是如何一步一步操作, 最终使问题出现的：

将系统语言切换成 '中文' （或者香港的繁体中文环境）
启用 'Beta 版：使用 Unicode UTF-8 提供全球语言支持' 选项
重启电脑，启动软件端，即可发现错误

**Comment by miaomiaosoft** [comment]
这个已经在常见问题里说明了，此程序与此选项无法同时工作。
https://support.qq.com/products/322047/faqs/95832
如果想同时工作，可以试试里面的用 Locale Emulator 运行panda

**Comment by wolovejing** [comment]
谢谢
