### ISSUE TITLE
关于识别之后主界面弹出

### ISSUE THREAD

**Issue by ghost** [miaomiaosoft/PandaOCR.Pro#25]
- 您好！
- Pro版能否增加识别文字之后主界面不弹出的选项（就是f4+自动复制实现后台连续识别并复制，现在Pro版每次识别之后窗口都会弹出需要关闭，稍显多余）。

**Comment by miaomiaosoft** [comment]
别启用预览弹窗呗

**Comment by miaomiaosoft** [comment]
如果你指的是主界面，那是你自己改了设置里的强制显示窗口，默认是不显示的
