### ISSUE TITLE
如何关闭更新提示弹窗

### ISSUE THREAD

**Issue by StevenLxQAQ** [miaomiaosoft/PandaOCR.Pro#27]
如题，thx

**Comment by miaomiaosoft** [comment]
你是哪个版本，可否告知不升级理由

我建议你能及时更新以解决一些问题
更新方法可参考：https://support.qq.com/products/322047/faqs/98846

**Comment by StevenLxQAQ** [comment]
工作电脑 使用相对稳定的情况下，想尽可能减少更新频率，或者手动更新，非自动弹窗提示

**Comment by miaomiaosoft** [comment]
那需要编辑程序配置文件，在[调试配置]下或配置最后添加以下两行：

#升级提示：0=总是提示 | 1-7为只在特定星期提示（以周日开始：1=周日 2=周一 依此类推）
升级提示=0

注意：此参数只在保留的两个旧版中有效，对过期版本无效

**Comment by StevenLxQAQ** [comment]
ok thx
