### ISSUE TITLE
程序的自启动是怎么完成的？

### ISSUE THREAD

**Issue by yi-Xu-0100** [miaomiaosoft/PandaOCR.Pro#3]
我在任务管理器的启动项中没找到，不是修改注册表吗？

**Comment by yi-Xu-0100** [comment]
我个人多次尝试，没法完成自启动，系统是

版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎5/‎13
操作系统内部版本	19042.985
体验	Windows Feature Experience Pack 120.2212.2020.0

**Comment by miaomiaosoft** [comment]
要管理员权限运行
要么自己把快捷方式放到系统的启动目录

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 好的，谢谢！
