### ISSUE TITLE
文字识别只能识别一定区域

### ISSUE THREAD

**Issue by sayapalayer** [miaomiaosoft/PandaOCR.Pro#31]
截图识别时只能识别左上角半侧的区
且识别区域是放大像素的
<img width="1720" alt="识别2" src="https://user-images.githubusercontent.com/54936432/142006700-a5301571-92af-4617-b1cb-3ef358a24968.png">
<img width="1720" alt="识别" src="https://user-images.githubusercontent.com/54936432/142006702-9cc52d9b-a45d-4aff-9672-168e00b6970f.png">

**Comment by miaomiaosoft** [comment]
为什么不在反馈前先查看教程 - 常见问题解决呢

**Comment by sayapalayer** [comment]
> 为什么不在反馈前先查看教程 - 常见问题解决呢
两种方法均尝试 没有用啊

**Comment by miaomiaosoft** [comment]
所有遇到的人这样操作都没问题
建议你重新认真查看教程照做一遍

**Comment by sayapalayer** [comment]
好的 谢谢
