### ISSUE TITLE
win7 双击打开后没报错 任务栏有图标 但是没有程序界面，怎么点都没有

### ISSUE THREAD

**Issue by superabbite1** [miaomiaosoft/PandaOCR.Pro#32]
win7 双击打开后没报错 任务栏有图标 但是没有程序界面，怎么点都没有

**Comment by miaomiaosoft** [comment]
我也WIN7无法复现，请重新下载最新版解压至C盘纯英文路径下运行，或排除是否被安全软件拦截，如果需要远程协助请进群找群主：700041212

**Comment by superabbite1** [comment]
路径确定是在纯英文路径下的。安全软件没有拦截。我是笔记本电脑，双显卡 不管是设置独显启动程序还是集显启动都不行

**Comment by miaomiaosoft** [comment]
我没有双显卡，可能也提供不了更多帮助，只能建议升到WIN10应该对双显卡有更好的支持

**Comment by miaomiaosoft** [comment]
此问题已在新版解决，故关闭
