### ISSUE TITLE
调用Snipaste错误

### ISSUE THREAD

**Issue by nicksean** [miaomiaosoft/PandaOCR.Pro#33]
调用Snipaste时，在Snipaste打开并且热键为F1的情况下提示：“Snipaste未打开或Snipaste热键不是F1”

**Comment by miaomiaosoft** [comment]
我是基于桌面版，可能你用的商店版？

**Comment by nicksean** [comment]
使用F4调用

**Comment by nicksean** [comment]
对，用的商店版

**Comment by miaomiaosoft** [comment]
我是WIN7系统 用不了商店版  可能两个版本有一些不同  目前建议用桌面版应该可以解决

**Comment by nicksean** [comment]
好的，那先用系统内置截图吧，谢谢

**Comment by miaomiaosoft** [comment]
如果不嫌麻烦可加群 700041212 找群主  需要远程看一下哪个地方不同
如不需要请忽略

**Comment by nicksean** [comment]
已加群，等通过中

**Comment by miaomiaosoft** [comment]
新版应该已解决此问题
