### ISSUE TITLE
请问软件用什么GUI库写的？

### ISSUE THREAD

**Issue by itfanr** [miaomiaosoft/PandaOCR.Pro#38]
很喜欢在win下搞单exe的程序，目前我没找到比较好用的方案。感谢。

**Comment by miaomiaosoft** [comment]
已收到您的邮件，我会尽快在5小时内回复！谢谢！---- 此邮件为假期自动回复

**Comment by itfanr** [comment]
@miaomiaosoft  winform 吗？

**Comment by miaomiaosoft** [comment]
winform不就是一种类库吗，我说了是没用什么库，你就理解成用API动态创建的界面吧

**Comment by itfanr** [comment]
@miaomiaosoft 那就是 MFC  喽？
