### ISSUE TITLE
在锁屏恢复时触发截图识别

### ISSUE THREAD

**Issue by yi-Xu-0100** [miaomiaosoft/PandaOCR.Pro#4]
我不确定是触发了截图识别还是触发了主程序。在双屏模式下，和 GDI 模式下均能触发。

在打开需要管理员授权的软件时，授权完也会触发。造成需要按 esc 取消识别。不知道是不是我个人问题还是？

**Comment by miaomiaosoft** [comment]
可能是边角触发功能导致的，无法与双屏区分
另外可以不用重发新帖

**Comment by yi-Xu-0100** [comment]
@miaomiaosoft 寻思是不同的问题，所以多开一个 issue 。方便对不同问题进行区分 😂

> 可能是边角触发功能导致的，无法与双屏区分

禁用后，恢复了，如果再触发再开吧 😊
