### ISSUE TITLE
是否可以新增VISA之類的付費方式？

### ISSUE THREAD

**Issue by Yusei-StarDust** [miaomiaosoft/PandaOCR.Pro#46]
如題，想要解鎖專業版，但是無法使用現有的兩種方式付費_(:з」∠)_不知是否可以提供其他如VISA/Mastercard等的付費方式，或是上架Microsoft Store之類的來另外用信用卡支付……

**Comment by miaomiaosoft** [comment]
看样子你不是大陆人，香港或台湾？
我也没有你说的那些支付方式，需要的话可以赠送一个激活码，请将机器码发我邮箱。

同时要说明一下，软件接入的多数都是中国的接口服务，大多数接口在开通前是需要实名认证的，至少也需要手机认证（但不确认非大陆手机是否可行， 需自行尝试）。

**Comment by Yusei-StarDust** [comment]
來自台灣，無法付費支持真的很不好意思_(:з」∠)_那請問email中需要另外註記什麼嗎(例如表明寄信人確實是提出issue的那個人之類的)？

**Comment by miaomiaosoft** [comment]
只提供机器码即可

**Comment by Yusei-StarDust** [comment]
了解，真的非常感謝！
