### ISSUE TITLE
文本编辑出现输入法中英文闪跳，无法切换到英文

### ISSUE THREAD

**Issue by SmallRob** [miaomiaosoft/PandaOCR.Pro#48]
识别后需要进行简单文本编辑，系统自带输入法无法完成中文切换，在已是中文状态仍然无法在文本框中输入中文。
状态：开始了按键显示
系统版本：win11

**Comment by SmallRob** [comment]
开启了按键显示，文本框一直刷，导致无法输入中文。

**Comment by miaomiaosoft** [comment]
按键显示功能已经存在几年了，从没遇过会影响输入的问题，还是排查你的系统是否有问题或冲突 或者直接禁用此功能。

**Comment by miaomiaosoft** [comment]
似乎和按键显示功能无关，请尝试此解决方案：https://support.qq.com/products/322047/faqs/119485
