### ISSUE TITLE
填入私有API Key后依然显示错误

### ISSUE THREAD

**Issue by taowenyin** [miaomiaosoft/PandaOCR.Pro#54]
填入私有API后使用截图ocr还是这个错误，网络功能一切正常，使用了百度OCR和合合OCR都是一样的结果，用演示OCR就正确。
---------------------------------------------------
当前识别接口未返回任何数据，可能为以下原因：

1. 图像中不包含任何可识别字符数据，请更换更清晰的图像。
2. 像素过大，在线接口通常限制最长4000像素，请缩小后重试！
3. 公用演示接口暂时失效，请重试或更换更稳定的私用API接口。
4. 私用API接口未配置或错误，请检查或重新配置（参照教程）。
5. 网络不稳定或连接故障，请检查防火墙或网络环境是否连接正常。

如果不想注册OCR接口，也可以尝试免注册无限制使用的离线OCR。

**Comment by miaomiaosoft** [comment]
激活了吗？合合接口需要激活后可使用！

**Comment by taowenyin** [comment]
激活了

——陶文寅

**Comment by miaomiaosoft** [comment]
这两个接口我这测试都没有问题，所以有问题的地方可能是你没有完全按教程操作，请重新尝试。
如果是识别日文  请在设置中将识别语言设为日语
如果自己无法解决请点反馈按钮进群
