### ISSUE TITLE
有无检测到固定区域内容变动自动识别的可能性？

### ISSUE THREAD

**Issue by tamakyi** [miaomiaosoft/PandaOCR.Pro#60]
如题所示

**Comment by miaomiaosoft** [comment]
配置文件：自动固定截图 部分

**Comment by tamakyi** [comment]
> 配置文件：自动固定截图 部分

看到了 谢谢

**Comment by Catnipll** [comment]
能不能不要强制升级新版呀.......现在检测到旧版直接强制退出，强迫升级新版.........

**Comment by Catnipll** [comment]
> 配置文件：自动固定截图 部分

能不能不要强制升级新版呀.......现在检测到旧版直接强制退出，强迫升级新版.........

**Comment by tamakyi** [comment]
老哥你单独开个issus啊，这评论作者没收到我收到了🤣



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [miaomiaosoft/PandaOCR.Pro] 有无检测到固定区域内容变动自动识别的可能性？ (Issue #60)




  
配置文件：自动固定截图 部分
  
能不能不要强制升级新版呀.......现在检测到旧版直接强制退出，强迫升级新版.........

**Comment by miaomiaosoft** [comment]
> > 配置文件：自动固定截图 部分
> 
> 能不能不要强制升级新版呀.......现在检测到旧版直接强制退出，强迫升级新版.........

旧版有一些严重问题需要升级才能解决，目前软件已经比较稳定，强制升级会越来越少。
另外有问题请新开帖子，不要在别人的帖子下回复。
