### ISSUE TITLE
[功能讨论]更便捷的设置

### ISSUE THREAD

**Issue by Ethkuil** [miaomiaosoft/PandaOCR.Pro#63]
（首先非常感谢作者编写出这样一个好用的软件。功能、交互的体验都很好。）

---

需求：切换到另一识别语言。

我目前是这样操作的：任务栏点开PandaOCR - 点开设置 - 切换识别语言 - 关掉设置。

如果可以的话，设置快捷键会更加方便。

一种供参考的实现：
按快捷键后弹出形如下图的小窗口供切换。
![image](https://user-images.githubusercontent.com/77615248/188608720-9d173c3c-e687-4719-8db4-86041f608cc6.png)

顺便谈谈我对 设置「识别语言、朗读语言、翻译来源、翻译目标」这些选项的理解。个人认为这些选项应该是和实际内容强关联的，因此可能不适合作为全局设置。

因此如果让我设计UI的话，我会把「设置识别语言」移动到「识别图形区」附近，其他几个同理。这样可能会再次大幅提高易用性。

这是我的想法，如果您觉得也有一定道理的话可以考虑一下。欢迎讨论。

**Comment by miaomiaosoft** [comment]
界面上已经没有更多合适的地方放设置组件了，至于按热键后弹出相应窗口 我感觉没有 鼠标右键点击某处后弹出语言选择菜单方便。
如果添加一个热键，事实上又要添加一个新的热键配置项，因为肯定会有人想要设置自己喜欢的热键。

我设想是点击某处后弹出所有语言的更改菜单，而不是图像区放一个，识别和翻译区又放一个。
至于鼠标点击何处触发，目前我还没想到主界面哪个地方合适。

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2022-10-25_4-45-14](https://user-images.githubusercontent.com/4084875/197626375-b5a41edf-5f3b-4dff-b764-48379e6d15aa.jpg)

如图，下个版本将在此处增加语言更改右键菜单
如果已激活专业版可入群：700041212 下载测试版
