### ISSUE TITLE
期待有一天能开放更多键位组合的快捷键设法

### ISSUE THREAD

**Issue by 6Tom** [miaomiaosoft/PandaOCR.Pro#65]
两个键的快捷键，只要在稍微复杂一点的软件中几乎不可能不冲突，比如photoshop，indesign，autocad，word，excel等

特别是像photoshop、indesign，几乎3个键位都很难不冲突

期待有一天能开放3甚至4~5个键位的设法，也期待可以组合win键

祝生活愉快

**Comment by miaomiaosoft** [comment]
你是指截图热键吗？
目前除了热键能触发截图识别外，还有边角触发截图（例如鼠标移至屏幕左上角）、鼠标侧键都可以代替热键。
可以尝试

**Comment by 6Tom** [comment]
好的，感谢回复
