### ISSUE TITLE
弹窗颜色选择

### ISSUE THREAD

**Issue by Nshandeshu** [miaomiaosoft/PandaOCR.Pro#66]
弹窗字体颜色默认是0=黄色
如果我想要更换别的颜色
该如何选择另外的颜色相应得数字

![2](https://user-images.githubusercontent.com/65987838/191920668-bedec9ce-12fb-48eb-8e4d-b3beda04d66e.jpg)

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2022-9-23_17-59-59](https://user-images.githubusercontent.com/4084875/191937210-173efd19-307f-4897-b9a6-7c5c6498b1f1.jpg)
右键菜单

**Comment by Nshandeshu** [comment]
> 

好的 找到了
