### ISSUE TITLE
开启 "精简显示方式" 后设置界面显示不全

### ISSUE THREAD

**Issue by huanghuanhuahuh** [miaomiaosoft/PandaOCR.Pro#67]
系统win10(19044.2006), 显示器21.5英寸1080p系统缩放100%
[![2022-09-24-214236.png](https://i.postimg.cc/4xG2bPfw/2022-09-24-214236.png)](https://postimg.cc/6yHhBdGG)

**Comment by miaomiaosoft** [comment]
这是已知问题啊，在你启用这个模式的时候本来就会有提示告知的，但提示被你禁用了。
![BaiduShurufa_2022-9-25_3-4-54](https://user-images.githubusercontent.com/4084875/192114530-fd96e8c2-30fe-43da-84db-09f257f1fb99.jpg)
