### ISSUE TITLE
可以添加批量识别图片后到一个文本的功能吗，类似Umi的

### ISSUE THREAD

**Issue by ImJING** [miaomiaosoft/PandaOCR.Pro#68]
可以添加批量识别图片后到一个文本的功能吗，类似Umi的

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2022-9-25_3-6-43](https://user-images.githubusercontent.com/4084875/192114585-df02eaab-6182-4750-aaf3-7d988380a2fe.jpg)

事实上已有此功能且默认启用
