### ISSUE TITLE
无法显示程序主窗口

### ISSUE THREAD

**Issue by nita0318** [miaomiaosoft/PandaOCR.Pro#7]
版本5.28
已设置DEP例外，高DPI缩放替代为应用程序，管理员运行
可以看到托盘图标，任务栏程序图标，鼠标放在程序任务栏图标上可以看到预览画面，可以看到“欢迎使用PandaOCR.Pro专业版”的系统通知
但是单击任务栏图标或托盘图标并不能显示pandaocr pro程序主界面
pandaocr 2.69可以正常显示程序窗口并使用
没有杀软拦截，wiki没有找到解决办法

**Comment by miaomiaosoft** [comment]
700041212  方便的话加一群，并下载运行anydesk，可能要远程看看
