### ISSUE TITLE
每次重启电脑后主程序消失

### ISSUE THREAD

**Issue by wulinfa** [miaomiaosoft/PandaOCR.Pro#71]
每次重启电脑后，就发现程序没自动启动（快捷方式已放入开机启动文件夹），然后手动去程序文件夹启动，就发现主程序消失了，
只有主程序消失了，其他生成的文件夹和配置文件都还在，
然后我只能去压缩包再拖一个主程序出来放在原处，再双击启动，
不是偶尔发生，是每次都会发生，
系统win10，熊猫版本5.43
orz
help

**Comment by miaomiaosoft** [comment]
https://support.qq.com/products/322047/faqs/95283
某些杀软比较流氓不给提示和选择直接强行删除 ，需要自行加白。
