### ISSUE TITLE
闹鬼了，每次过段时间EXE就不见了

### ISSUE THREAD

**Issue by fuyubi** [miaomiaosoft/PandaOCR.Pro#72]
卡巴和火绒开着，win11自带的保护程序处于关闭状态，卡巴设置了排除，信任。发觉好像是每次系统息屏睡眠过一会唤醒就没了，pandaocr被退出，exe执行程序同时消失不见，三个杀软的日志也没有东西。

**Comment by miaomiaosoft** [comment]
自带杀毒没那么容易完全关闭，自己谷歌搜索下如何禁用，其他杀毒也尝试加个白名单。
EXE本身不会自己删除，所以需要自行解决。
