### ISSUE TITLE
更新的时候能不能生成一个配置文件

### ISSUE THREAD

**Issue by 8ty** [miaomiaosoft/PandaOCR.Pro#73]
这样子直接拖动到新的文件夹就可以，不用再一次密钥什么的

**Comment by miaomiaosoft** [comment]
![image](https://user-images.githubusercontent.com/4084875/201188894-182b61a2-cb34-4727-8452-20ae12da7ba0.png)

5.43之后的版本都可以一键自动更新，保留所有配置，并不需要自己额外操作。

**Comment by 8ty** [comment]
好的，感谢
