### ISSUE TITLE
PandaOCR.PRO 5.44 在win10下无反应

### ISSUE THREAD

**Issue by blog2i2j** [miaomiaosoft/PandaOCR.Pro#77]
64位的win10 1903版, pro 5.44启动后CPU长期占用超过10%, 不能显示出界面, 就跟无反应一样.

**Comment by miaomiaosoft** [comment]
没有收到更多此类反馈且此软件主要群体也是WIN10，看你描述可能是你系统中其他软件对OCR进行了某些挂载操作导致无法退出，请自行排查。
