### ISSUE TITLE
可以增加调节窗口大小的功能吗？

### ISSUE THREAD

**Issue by LKYZXY** [miaomiaosoft/PandaOCR.Pro#81]

**Comment by miaomiaosoft** [comment]
鼠标放到窗口右下角即可拖拉调整啊，和别的普通窗口没两样

**Comment by LKYZXY** [comment]
> 鼠标放到窗口右下角即可拖拉调整啊，和别的普通窗口没两样

哈哈哈哈哈，四条边和左边两个角都试了一下不行，笑死了，可以把这个写到教程里面，今天在教程里面也没有找到（也有可能是没仔细看），软件很好用

**Comment by LKYZXY** [comment]
> 鼠标放到窗口右下角即可拖拉调整啊，和别的普通窗口没两样

我是感觉默认情况下还是有点大

**Comment by miaomiaosoft** [comment]
文本区右键  显示方式  精简
