### ISSUE TITLE
不知道为什么出现今日体验次数超出限制

### ISSUE THREAD

**Issue by hetintin** [miaomiaosoft/PandaOCR.Pro#83]
这本是我今天第一次使用，它却显示我的体验次数超出限制，很莫名其妙
我感觉出现这种情况的主要原因是当天或前一天升级软件造成的，几乎每次升级软件后都会有这个问题
而我当天绝对没有使用软件超过3次
![image](https://user-images.githubusercontent.com/61347434/233253974-a71b8985-0772-414b-96a9-c33c5d701621.png)

**Comment by miaomiaosoft** [comment]
你没激活用的又是演示接口本来就是次数限制
