### ISSUE TITLE
不能调整窗口吗？配置设置云同步

### ISSUE THREAD

**Issue by kunpeng9** [miaomiaosoft/PandaOCR.Pro#86]
这个是会员功能还是没有调整功能，窗口太大了，目前在用天若ocr中，19年就开始用了
什么时候支持配置云同步功能，能搞个网页吗，类似天若的网页，可以搜到的，以前配置丢失了一些次，现在用的本地备份，更新又要操作1遍，总之本地配置真的很麻烦啊
能云同步就云同步吧，这点数据量很少

**Comment by miaomiaosoft** [comment]
什麼更新？
軟件更新只需要點一鍵自動升級即可，手動升級也只是覆蓋舊版文件即可，並不會影響配置。
不會有雲同步，根本就少的可憐會用的到。
