### ISSUE TITLE
文字识别量和翻译量显示

### ISSUE THREAD

**Issue by kunpeng9** [miaomiaosoft/PandaOCR.Pro#87]
什麼更新？
軟件更新只需要點一鍵自動升級即可，手動升級也只是覆蓋舊版文件即可，並不會影響配置【不行，之前试了好些次了。老是更新失败，只能下载安装包的方式来覆盖安装】
不會有雲同步，根本就少的可憐會用的到。【如果有的话会减少很多麻烦，减少潜在的担忧，本地最好不保存配置，害怕硬盘暴毙，最好还是希望能升级，云端化是大趋势】
窗口縮小可以在文本區右鍵 - 顯示方式 - 精簡方式 切換【不行，窗口还是太大了】

文字识别量和翻译量显示=能否统计所有接口的文字识别量和翻译量，类似于百度翻译的开发平台，我会经常查看api使用量，但是panda好多个api，使用量都在各个平台，能不能软件端进行统计
![天若_20230630152220](https://github.com/miaomiaosoft/PandaOCR.Pro/assets/44609485/312ab477-b54b-4d85-854a-e536838ffe2a)

你知道这个吗，哔哩哔哩很多视频也有讲过的，我用了几年了，天若ocr用了大概4年，去年后没怎么更新了
我的quicker推荐码9620-7065，里面有大量的文字识别动作，quicker将会替代很多比较简单+常年没怎么更新的半死的软件，高于一定复杂度的软件会存活，低于的会死透，功能会被吸收、合并到quicker里面，quicker不管是调整动作，配置备份，更新动作都非常方便，1次更新大批

[分享的动作 - Quicker](https://getquicker.net/Share/Actions?filter=%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB)
[截图OCR - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=ba82e11a-f845-4ca3-44ee-08d690b5076c) 这个动作可供吸收，连续识别非常好用+非常刚需

**Comment by miaomiaosoft** [comment]
你是提問還是跑這推廣？怎麼推薦碼都出來了？？？
