### ISSUE TITLE
什么时候会出黑夜模式

### ISSUE THREAD

**Issue by kunpeng9** [miaomiaosoft/PandaOCR.Pro#88]
晚上使用非常刺眼，能出黑夜模式的话就出吧、quicker提了一些次至今没有=1大劣势，
quicker好多识别动作，使用人数非常多，功能都可供吸收的，我安装了一些但是用的不太好，主要之前用天若更多，习惯了

**Comment by miaomiaosoft** [comment]
如果你要提出什麼功能直接就本軟件提即可，不需要與其他軟件相比，每個軟件都有自己有特色和風格。
暗黑模式不會有。
另外很重要的一點，你不用一直發新帖，你幾個問題完全可以在同一個帖子裏說明。
