### ISSUE TITLE
pro版无法运行啊

### ISSUE THREAD

**Issue by muldaph** [miaomiaosoft/PandaOCR.Pro#9]
win10 LTSC X64系统，一运行就显示0x0000000000CE1320指令引用了0x0000000000CE1320。该内存不能为written。

**Comment by miaomiaosoft** [comment]
没人报过这种错误，请参照教程里的常见问题解决，如果都不行我也没啥办法，可能系统问题：
https://support.qq.com/products/322047/faqs-more#classifyId=58619
