### ISSUE TITLE
固定截图热键 1-9是啥啊 看不懂

### ISSUE THREAD

**Issue by KrysMs1** [miaomiaosoft/PandaOCR.Pro#91]
固定截图热键=1之后 快捷键写在哪个后面 比如F5 F6 F7

#固定截图热键：0=禁用 | alt/ctrl+!/1 | !为主键区数字键 | 1为小键盘区数字键 | 示例：alt+! 或 alt+1
固定截图热键=0
固定截图区域=1
01=1|486|119|139|25
02=2|571|523|192|26
03=3|674|1028|169|28
04=4|210|939|907|37
05=5|574|456|193|35
06=6|500|500|300|200
07=7|500|500|300|200
08=8|500|500|300|200
09=9|500|500|300|200
10=10|500|500|300|200

**Comment by KrysMs1** [comment]
还是必须设置三个键同时才能截

**Comment by miaomiaosoft** [comment]
不是提供了两个示例吗，随便取一个填上就知道什么效果了。
