### ISSUE TITLE
固定截图热键怎么改 文本里的提示看不懂

### ISSUE THREAD

**Issue by KrysMs1** [miaomiaosoft/PandaOCR.Pro#92]
比如我想设置02为F5 03=F6 怎么写

#固定截图热键：0=禁用 | alt/ctrl+!/1 | !为主键区数字键 | 1为小键盘区数字键 | 示例：alt+! 或 alt+1
固定截图热键=0
固定截图区域=1
01=1|505|90|169|37
02=2|571|523|192|26
03=3|674|1028|169|28
04=4|210|939|907|37
05=5|574|456|193|35
06=6|500|500|300|200
07=7|500|500|300|200
08=8|500|500|300|200
09=9|500|500|300|200
10=10|500|500|300|200

**Comment by KrysMs1** [comment]
作者给我关闭了啊 我说呢 还以为没发出来  换头像找到历史发帖了  

哪有两个示例？    01=1|505|90|169|37   02=2|571|523|192|26  这两个？  还是直接说一下  比如我02设置快捷键F5 03快捷键F6 怎么写

**Comment by miaomiaosoft** [comment]
带 # 号开头那行是注释行，里面最后就是示例

固定截图热键=alt+1

填一个就能自动为十个列表都绑定热键
