### ISSUE TITLE
截屏的范围被缩小了，只剩整个屏幕的四分之一可以截图 求助求助🙁

### ISSUE THREAD

**Issue by Saltyfishhhhhh** [miaomiaosoft/PandaOCR.Pro#93]
![屏幕截图 2024-02-17 165125](https://github.com/miaomiaosoft/PandaOCR.Pro/assets/87053122/7c6cf851-2a8b-4d66-816b-59daa54b68f6)
![屏幕截图 2024-02-17 165125](https://github.com/miaomiaosoft/PandaOCR.Pro/assets/87053122/187e86e3-af2f-4f9b-a34b-ff2eb916ceab)

**Comment by miaomiaosoft** [comment]
教程里常见问题第一条就是
https://support.qq.com/products/322047/faqs/95279

**Comment by Saltyfishhhhhh** [comment]
感谢感谢 不过关机重启就好了 之前从来没有这种
