### ISSUE TITLE
打开以后都是乱码，软件和使用必读，求助

### ISSUE THREAD

**Issue by neo-258** [miaomiaosoft/PandaOCR.Pro#95]
类似这种：
5. ³ÌÐòµÄ¿ª·¢Óë·¢²¼¾ùÔÚESET NOD32É±Èí±£»¤µÄ»·¾³ÖÐÍê³É£¬Èç¹ûÊ¹ÓÃ¹ý³ÌÖÐ£¬ÄúÏµÍ³ÖÐÄ³ÖÖ¡°°²È«¡±Èí¼þ¼á³Æ¡¸·¢ÏÖÄ¾Âí¡¹£¬ÄÇÃ´´ËÇéÐÎ½«¿¼ÑéÄúµÄÅÐ¶ÏÁ¦£»

**Comment by miaomiaosoft** [comment]
点教程按钮 有现成答案
