### ISSUE TITLE
谷歌翻译怎么配置

### ISSUE THREAD

**Issue by EverGS** [miaomiaosoft/PandaOCR.Pro#96]
请问谷歌翻译怎么配置。翻译选谷歌翻译后截图识别不出结果。

**Comment by miaomiaosoft** [comment]
需要科学上网即可

**Comment by EverGS** [comment]
你好，打开了科学上网工具，设置了全局，但是还是没办法翻译
![image](https://github.com/miaomiaosoft/PandaOCR.Pro/assets/14147393/ceb86e59-cd14-4de5-83dd-ca362c818feb)

**Comment by miaomiaosoft** [comment]
试了下是没问题的，但最近谷歌翻译服务器有稳定性问题，时好时不好，可能需要等谷歌自行修复。

**Comment by miaomiaosoft** [comment]
抱歉，重新测试了下，谷歌服务器稳定性应该没问题，但最近可能谷歌更换了协议或是某些东西，导致软件在使用旧的连接组件时会变的很慢甚至无法返回数据，目前换用CURL访问后已经恢复。

如果你已经激活专业版可以入群下载测试版，没有的话可能需要等待新版更新推送。
