### ISSUE TITLE
当前运行环境异常，请尝试特程序移至单独的自录中使用

### ISSUE THREAD

**Issue by hexw** [miaomiaosoft/PandaOCR.Pro#97]
提示：
当前运行环境异常，请尝试特程序移至单独的自录中使用或者联系此邮箱：miaomiaosoft@qq.com

**Comment by hexw** [comment]
已移动到单独目录

**Comment by miaomiaosoft** [comment]
重启一次电脑并优先运行OCR，可能和其他编程类程序冲突

**Comment by hexw** [comment]
与eclipse 冲突,关掉eclipse好了
