### ISSUE TITLE
自动更新速率异常

### ISSUE THREAD

**Issue by madman43** [miaomiaosoft/PandaOCR.Pro#98]
刚开始卡住很久直接4096mb 
![image](https://github.com/user-attachments/assets/ce4cbc26-6792-4555-8843-72c3aaab003c)
后面速率也是有问题，15m下载十多分钟，下载速度又是1m 2m/s
![GIF 2024-9-19 周四 10-24-59](https://github.com/user-attachments/assets/d5dbd8cc-19e9-4463-a829-d39f6e856fe7)

**Comment by miaomiaosoft** [comment]
这个主要和每个人网络环境有关，建议直接网盘下载覆盖。
